[package]
name = "egui_samples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "examples/*"
]

[dependencies]
eframe = "0.21"
chrono = "0.4"
slotmap = "1.0"